ifeq ($V, 1)
  Q =
  S =
else
  S ?= -s
  Q ?= @
endif

export V Q S

#
# if you want the ram-disk device, define this to be the
# size in blocks.
#
RAMDISK_START ?= 256
# Tool for Image building
BUILD = RAMDISK_START=$(RAMDISK_START) ./build.sh

AS      = as
AFLAGS  = -g --32
LD      = ld
LDFLAGS = -m elf_i386
CC      = gcc
CFLAGS  = -g -m32 -fno-builtin -fno-stack-protector -fomit-frame-pointer -fstrength-reduce #-Wall

CPP     = cpp -nostdinc
AR      = ar
STRIP   = strip
OBJCOPY = objcopy